
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template
drivername=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://localhost:3306/webnovel?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
username=root
password=KHAi@2692004


